### ISSUE TITLE
Add sort order in row

### ISSUE THREAD

**Issue by avdyushin** [avdyushin/FlowLayout#1]
Need to sort items for centered alignment in row based on indexPath.row:

```
[itemsInRow sortUsingComparator:^NSComparisonResult(UICollectionViewLayoutAttributes *obj1, UICollectionViewLayoutAttributes *obj2) {
    return obj1.indexPath.row > obj2.indexPath.row;
}];
```

**Comment by purplepeng** [comment]
I also found the problem of item's sort and the above code works. I think you're better to merge the code. Thanks.
